language: cpp
compiler: gcc
dist: trusty

addons:
  apt:
    sources:
      - sourceline: "deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe"
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - libboost-all-dev
      - libdlib-dev
      - libopenblas-dev
      - libgnuplot-iostream-dev

install:
  - export CC=gcc-7
  - export CXX=g++-7
  - cd "${TRAVIS_BUILD_DIR}"

script:
  - cmake .
  - cmake --build .
  - cmake --build . --target package

deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: master
    script:
    - curl -T kkmeans-1.1.$TRAVIS_BUILD_NUMBER-Linux.deb -upetrljutik:$BINTRAY_API_KEY "https://api.bintray.com/content/petrljutik/kkmeans/kkmeans/$TRAVIS_BUILD_NUMBER/kkmeans-1.1.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
