dist: xenial
language: cpp
addons:
  apt:
    sources:
    - sourceline: "deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe"
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - libboost-all-dev
    - libopenblas-dev
    - libdlib-dev
script:
- export CC=gcc-7
- export CXX=g++-7
- cmake .
- cmake --build .
- cmake --build . --target package

deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: master
    script:
    - curl -T kkmeans-1.1.$TRAVIS_BUILD_NUMBER-Linux.deb -upetrljutik:$BINTRAY_API_KEY "https://api.bintray.com/content/petrljutik/kkmeans/kkmeans/$TRAVIS_BUILD_NUMBER/kkmeans-1.1.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
