language: cpp
compiler: gcc
dist: trusty

addons:
  apt:
    sources:
      - sourceline: "deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe"
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - libboost-all-dev
      - libdlib-dev
      - libopenblas-dev


before_script:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90
  - wget http://dlib.net/files/dlib-19.16.tar.bz2
  - tar xf dlib-19.16.tar.bz2
  - cd dlib-19.16
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config Release
  - sudo make install
  - sudo ldconfig
  - cd "${TRAVIS_BUILD_DIR}"


script:
  - cmake .
  - cmake --build .
  - cmake --build . --target package

deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: master
    script:
    - curl -T kkmeans-1.1.$TRAVIS_BUILD_NUMBER-Linux.deb -upetrljutik:$BINTRAY_API_KEY "https://api.bintray.com/content/petrljutik/kkmeans/kkmeans/$TRAVIS_BUILD_NUMBER/kkmeans-1.1.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
